language: python
before_install:
    - openssl aes-256-cbc -K $encrypted_3bd81e4a6a4c_key -iv $encrypted_3bd81e4a6a4c_iv -in appdev-soda-spanner-staging-b842e628aa41-orijtech.json.enc -out ~/creds.json -d

env:
    global:
        - GOOGLE_APPLICATION_CREDENTIALS=~/creds.json
        - RUNNING_SPANNER_BACKEND_TESTS=1
    jobs:
        - DJANGO_TEST_APPS="admin_changelist admin_custom_urls"
        - DJANGO_TEST_APPS="admin_docs admin_inlines admin_ordering"
        - DJANGO_TEST_APPS="aggregation aggregation_regress annotations basic"
        - DJANGO_TEST_APPS="bulk_create custom_columns custom_methods custom_pk datatypes"
        - DJANGO_TEST_APPS="dates datetimes defer defer_regress delete delete_regress"
        - DJANGO_TEST_APPS="db_functions empty expressions_window fixtures"
        - DJANGO_TEST_APPS="fixtures_regress filtered_relation from_db_value"
        - DJANGO_TEST_APPS="indexes known_related_objects lookup max_lengths m2m_and_m2o m2m_intermediary m2m_multiple"
        - DJANGO_TEST_APPS="m2m_recursive m2m_regress m2m_signals m2m_through"
        - DJANGO_TEST_APPS="m2m_through_regress m2o_recursive managers_regress many_to_many"
        - DJANGO_TEST_APPS="many_to_one"
        - DJANGO_TEST_APPS="many_to_one_null model_fields"
        - DJANGO_TEST_APPS="multiple_database mutually_referential nested_foreign_keys"
        - DJANGO_TEST_APPS="null_fk null_fk_ordering null_queries one_to_one or_lookups ordering"
        - DJANGO_TEST_APPS="queries.test_bulk_update queries.test_explain queries.test_iterator queries.test_q queries.test_qs_combinators queries.test_query"
        - DJANGO_TEST_APPS="queries.tests"
        - DJANGO_TEST_APPS="raw_query reserved_names reverse_lookup select_related select_related_onetoone sitemaps_tests"
        - DJANGO_TEST_APPS="sites_framework sites_tests string_lookup timezones transactions update view_tests

python:
    - "3.7"
cache: pip
install:
    - pip install . tox-travis flake8 isort
script:
    - tox
    - flake8
    - isort --recursive --check-only --diff
    - bash django_test_suite.sh
